### Santé
GET http://127.0.0.1:8787/api/health

### Disponibilités
GET http://127.0.0.1:8787/api/availability?date=2026-09-16

### Recherche client
GET http://127.0.0.1:8787/api/clients?search=LAROCHELLE

### Rendez-vous du jour
GET http://127.0.0.1:8787/api/appointments?date=2026-09-16
